PCB: false
batchsize: 32
color_jitter: false
data_dir: ../PKUSketchRE-ID_V1/pytorch
droprate: 0.5
erasing_p: 0.5
fp16: false
gpu_ids: '0'
lr: 0.1
name: beneran56
nclasses: 150
stride: 2
train_all: true
use_resnet110: false
use_resnet110_fc1024: false
use_resnet110_fc128: false
use_resnet110_fc256: false
use_resnet110_fc768: false
use_resnet110_spp: false
use_resnet32: false
use_resnet44: false
use_resnet56: true
use_resnet56_fc1024: false
use_resnet56_fc128: false
use_resnet56_fc256: false
use_resnet56_fc768: false
use_resnet56_spp: false
warm_epoch: 5
